#	Ongoing: 2022-08-22T21:56:48AEST multiple makefiles in a directory(?)
#	Ongoing: 2022-08-22T22:00:43AEST what option is producing the 'dSYM' directory (not produced in 01-hello-world)

CFLAGS=-Wall -g

clean:
	rm -f hello-world


