#	Ongoing: 2022-08-22T22:24:05AEST meaning of adding 'clean' to 'all' list? (cleans before building (why we have it first in 'all'))

CFLAGS=-Wall -g

all: clean printf-example 

clean:
	rm -f printf-example



